version: "3.7"

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  srefinal_app:

services:
  srefinal_app:
    image: srefinal_app
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - monitoring

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - /c/Users/gupra/Downloads/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9091:9090
    depends_on:
      - srefinal_app
    restart: always
    networks:
      - monitoring
    hostname: prometheus
